# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aaron "Hyperum" Cruz
email: unysnhyperum@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Aaron, but my fascination with aliases when I was younger caused
  much of my online presence to be attributed to the name 'Hyperum'. Here, I
  won't post very often but include detailed accounts when I do. This site will
  also be more personal, but my innermost thoughts be kept to myself, of
  course. Please enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aaronhyperum.github.io" # the base hostname & protocol for your site
twitter_username: aaronhyperum
github_username:  aaronhyperum

# Build settings
markdown: kramdown
